export const BUSQUEDA = 'BUSQUEDA'
export const RESUTLADOS_LUGARES = 'RESULTADOS_LUGARES'

export const DEFINIR_ORIGEN = 'DEFINIR_ORIGEN'
export const DEFINIR_DESTINO = 'DEFINIR_DESTINO'
export const INFO_VIAJE = 'INFO_VIAJE'